on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64-x86-64

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true
          target: x86_64-unknown-linux-gnu

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.7.3

      - name: clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: install cargo-license
        uses: actions-rs/cargo@v1.0.3
        with:
          command: install
          args: cargo-license

      - name: compile for unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --no-run --locked

      - name: unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu

      - run: |
          mkdir infinite-craft-logger
          cargo license \
            --authors \
            --do-not-bundle \
            --avoid-dev-deps \
            --avoid-build-deps \
            --filter-platform x86_64-pc-windows-gnu \
              > infinite-craft-logger/CREDITS
          VERSION_NAME=${GITHUB_REF##*/}
          if [[ $VERSION_NAME == "master" ]]; then
              VERSION_NAME=$(git rev-parse --short HEAD)
          elif [[ ${VERSION_NAME:0:1} == "v" ]]; then
              VERSION_NAME=${VERSION_NAME:1}
          fi
          echo "$VERSION_NAME" > infinite-craft-logger/VERSION.txt
          cp LICENSE README.md infinite-craft-logger/
          cp target/x86_64-pc-windows-gnu/release/infinite-craft-logger.exe infinite-craft-logger/
          zip -r infinite-craft-logger-windows.zip infinite-craft-logger
          rm infinite-craft-logger/*.exe
          cargo license \
            --authors \
            --do-not-bundle \
            --avoid-dev-deps \
            --avoid-build-deps \
            --filter-platform x86_64-unknown-linux-gnu \
              > infinite-craft-logger/CREDITS
          cp target/x86_64-unknown-linux-gnu/release/infinite-craft-logger infinite-craft-logger/
          zip -r infinite-craft-logger-linux.zip infinite-craft-logger

      - name: pre-release
        uses: softprops/action-gh-release@v2.2.1
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          files: |
            infinite-craft-logger-windows.zip
            infinite-craft-logger-linux.zip

      - name: tagged-release
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            infinite-craft-logger-windows.zip
            infinite-craft-logger-linux.zip
